package interview.algorithm.easy.answers;

import interview.algorithm.easy.questions.FindTheDifference;

/**
 * Given two strings s and t which consist of only lowercase letters.
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 * Find the letter that was added in t.
 * Example:
 * Input:
 * s = "abcd"
 * t = "abcde"
 * Output:
 * e
 * Explanation:
 * 'e' is the letter that was added.
 * Created by zhouxuan on 2016/12/8.
 */
public class FindTheDifferenceAns implements FindTheDifference {
    public char findTheDifference(String s, String t) {
        int result = 0;
        for (int i = 0; i < s.length(); i++) {
            result ^= s.charAt(i) ^ t.charAt(i);
        }
        result ^= t.charAt(t.length() - 1);
        return (char) result;
    }

    public static void main(String[] args) {
        String s = "abcd";
        String t = "abcde";
        FindTheDifference findTheDifference = new FindTheDifferenceAns();
        System.out.println(findTheDifference.findTheDifference(s, t));
    }
}
